### ISSUE TITLE
Wrong type with malice-plugins/yara

### ISSUE THREAD

**Issue by stanley101music** [YARAHQ/yara-forge#17]
I've added https://github.com/malice-plugins/yara/tree/master to the configuration file.
The error appears in `/main/rule_processors.py` in function `evaluate_yara_rule_score` at `line 517`
where the `meta_data` is `str` not `dict`, and thus doesn't have `items()`

Here's the original yara rule that caused this error from https://github.com/malice-plugins/yara/blob/master/rules/rats.yar
```
rule Albertino
{
	meta:
		author = " Kevin Breen <kevin@techanarchy.net>"
		date = "2014/04"
		ref = "http://malwareconfig.com/stats/AAR"
		family = "albertino"
		tags = "rat, albertino"

	strings:
		$a = "Hashtable"
		$b = "get_IsDisposed"
		$c = "TripleDES"
		$d = "testmemory.FRMMain.resources"
		$e = "$this.Icon" wide
		$f = "{11111-22222-20001-00001}" wide
		$g = "@@@@@@@@@@@"

	condition:
		all of them
}
```

and the `metadata` of the rule that is sent as the input of `evaluate_yara_rule_score` is
`'metadata': {'tags': 'ALBERTINO, RAT'}`

Compared to other normal metadata, it seems that the type of the value of `metadata` should be a list of dictionaries, 
while in this case, the type of the value is dictionary.

**Comment by Neo23x0** [comment]
This should fix the issues : https://github.com/YARAHQ/yara-forge/pull/18
